spring.application.name=demohosts
# specify configs for DB
spring.datasource.url=jdbc:mysql://demohost.mysql.database.azure.com:3306/datacenter?useSSL=true&requireSSL=true&trustServiceCertificate=true
#;myDbConn=DriverManager.getConnection(url, "Wafflezz", "ROro@20200217");
#jdbc:mysql://demohost.mysql.database.azure.com/datacenter?useSSL=true&requireSSL=true&trustServiceCertificate=true
spring.datasource.username=Wafflezz
spring.datasource.password=ROro@20200217

# keep these JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect